### ISSUE TITLE
Admission procedure should be done

### ISSUE THREAD

**Issue by RaianHossain** [RaianHossain/sbfni#12]

**Comment by santo1989** [comment]
![image](https://user-images.githubusercontent.com/65486217/170968937-f688bac4-e7e9-4b1f-a609-ff35870dc39b.png)
![image](https://user-images.githubusercontent.com/65486217/170968989-af86639f-2ebb-4108-b33e-02e01423b49b.png)
![image](https://user-images.githubusercontent.com/65486217/170969034-3d4250f6-7b6c-497a-9f92-72164f2cbb22.png)
