### ISSUE TITLE
Buttons should be recreated

### ISSUE THREAD

**Issue by RaianHossain** [RaianHossain/sbfni#6]
Some examples -> https://uicookies.com/css-buttons/

**Comment by santo1989** [comment]
primary choose 

![image](https://user-images.githubusercontent.com/65486217/171015962-f637c714-2fd8-4943-8555-33c06a3163c2.png)
![Uploading image.png…]()

**Comment by santo1989** [comment]
![image](https://user-images.githubusercontent.com/65486217/171016107-94899b87-47d1-4eae-810c-464178f87415.png)
