### ISSUE TITLE
Course details -> gap needed between two divs

### ISSUE THREAD

**Issue by RaianHossain** [RaianHossain/sbfni#9]

**Comment by santo1989** [comment]
![image](https://user-images.githubusercontent.com/65486217/170988053-53168690-9914-4a45-aaf9-79ea03390a04.png)
![image](https://user-images.githubusercontent.com/65486217/170988070-c3d3ba9a-745c-459f-b4b1-036706403d72.png)
![image](https://user-images.githubusercontent.com/65486217/170988122-b2bfe7c7-cf07-4514-879d-67527becec79.png)

![image](https://user-images.githubusercontent.com/65486217/170988164-0adc5d5d-d340-479a-a538-ec4d0d77534e.png)
![image](https://user-images.githubusercontent.com/65486217/170988212-114067a5-de36-4c4e-823b-72f7b547e2c5.png)
![image](https://user-images.githubusercontent.com/65486217/170988255-cf9eea35-cb70-453e-9334-641b075ced01.png)
![image](https://user-images.githubusercontent.com/65486217/170988281-e6e55e3c-19a9-4427-9274-1123a23a7922.png)
